"""
UserAccountControl flags to manipulate user account properties. [source](https://support.microsoft.com/en-us/help/305144/how-to-use-useraccountcontrol-to-manipulate-user-account-properties)
"""
enum UserAccountControl {
  SCRIPT
  ACCOUNTDISABLE
  HOMEDIR_REQUIRED
  LOCKOUT
  PASSWD_NOTREQD
  PASSWD_CANT_CHANGE
  ENCRYPTED_TEXT_PWD_ALLOWED
  TEMP_DUPLICATE_ACCOUNT
  NORMAL_ACCOUNT
  INTERDOMAIN_TRUST_ACCOUNT
  WORKSTATION_TRUST_ACCOUNT
  SERVER_TRUST_ACCOUNT
  DONT_EXPIRE_PASSWORD
  MNS_LOGON_ACCOUNT
  SMARTCARD_REQUIRED
  TRUSTED_FOR_DELEGATION
  NOT_DELEGATED
  USE_DES_KEY_ONLY
  DONT_REQ_PREAUTH
  PASSWORD_EXPIRED
  TRUSTED_TO_AUTH_FOR_DELEGATION
  PARTIAL_SECRETS_ACCOUN
}

type Query {
  """
  search against "sAmAccountName" attribute of users
  """
  userGetByUserName(userName: String!): [User]!
  """
  search against common name "cn" attribute of users
  """
  userGetByName(cn: String!): [User]!
  """
  fussy search against common name "cn" attribute of users.
  note depend on number of users this can be slow process.
  """
  userGetByNameApproxMatch(cn: String!): [User]!
  """
  based on criteria return not disabled users respecting userAccountControl flags
  """
  userGetDisabled(criteria: String): [User]!
  """
  based on criteria return not disabled users respecting userAccountControl flags
  """
  userGetNotDisabled(criteria: String): [User]!
  """
  based on criteria return user that are Locked Out
  """
  userGetLockedOut(criteria: String): [User]!
  """
  based on criteria return user accounts required a home directory respecting userAccountControl flags
  """
  userGetHomedirRequired(criteria: String): [User]!
  """
  based on criteria return not password never expire users respecting userAccountControl flags
  """
  userGetPasswordNeverExpires(criteria: String): [User]!
  """
  based on criteria return not password not required users respecting userAccountControl flags
  """
  userGetPasswordNotRequired(criteria: String): [User]!
  """
  based on criteria return user accounts respecting multiple userAccountControl flags
  """
  userGetByUserAccountControl(
    criteria: String
    accountControls: [UserAccountControl!]!
  ): [User]!
}
